In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("messy_ecommerce_sales_dataset.csv")
df.head()

,OrderID,CustomerID,CustomerName,Email,ProductID,ProductName,Category,Quantity,UnitPrice,DiscountPercent,TotalAmount,OrderDate,ShipDate,PaymentMethod,OrderStatus,ShippingCity,Country,CustomerRating
0,ORD104369,CUST3263,Ayaan Miller,ayaanmiller27@hotmail.com,P7565,Winter Jacket,Fashion,-1,10162.95,25,-7622.21,19-Jun-24,18-06-2024 03:42,Wallet,cancelled,Sydney,Australia,NaN
1,ORD109142,CUST3663,Mia Miller,miamiller52@outlook.com,P2000,Resistance Bands,Sports,4,11203.66,5,42573.91,09-17-2023,19-Sep-23,COD,Pending,NaN,UAE,6.0
2,ORD104638,CUST3028,Isabella Iyer,isabellaiyer@hotmail.com,P5250,Children's Story Book,books,1,13630.56,150,-6815.28,18-07-2024 21:05,27-07-2024,Net Banking,Pending,London,UK,3.0
3,ORD111342,CUST1115,David Singh,davidsingh@gmail.com,P7565,Winter Jacket,FASHION,10,20753.43,20,166027.44,21-02-2022 08:47,25-02-2022 08:47,wallet,Pending,Singapore,Singapore,6.0
4,ORD106560,CUST3690,mason garcia,masongarcia@gmail.com,P5284,Kitchen Knife Set,HOME & KITCHEN,5,9703.35,10,43665.08,30-07-2022,07-08-2022,Cash on Delivery,processing,SURAT,India,5.0

In [3]:
df.describe

<bound method NDFrame.describe of          OrderID CustomerID     CustomerName                        Email  \
0      ORD104369   CUST3263     Ayaan Miller    ayaanmiller27@hotmail.com
1      ORD109142   CUST3663       Mia Miller      miamiller52@outlook.com
2      ORD104638   CUST3028    Isabella Iyer     isabellaiyer@hotmail.com
3      ORD111342   CUST1115      David Singh         davidsingh@gmail.com
4      ORD106560   CUST3690     mason garcia        masongarcia@gmail.com
...          ...        ...              ...                          ...
13145  ORD107086   CUST1495   Reyansh Sharma    reyanshsharma71@gmail.com
13146  ORD105562   CUST3602   Krishna Miller  krishnamiller89@outlook.com
13147  ORD103403   CUST3206     Robert Patel        robertpatel@yahoo.com
13148  ORD109055   CUST2522  EVELYN MARTINEZ     evelynmartinez@gmail.com
13149  ORD110475   CUST3255   Amelia Reddy     ameliareddy@rediffmail.com

      ProductID            ProductName        Category  Quantity  UnitPrice  \
0         P7565          Winter Jacket         Fashion        -1   10162.95
1         P2000       Resistance Bands          Sports         4   11203.66
2         P5250  Children's Story Book           books         1   13630.56
3         P7565          Winter Jacket         FASHION        10   20753.43
4         P5284      Kitchen Knife Set  HOME & KITCHEN         5    9703.35
...         ...                    ...             ...       ...        ...
13145     P4418              Biography           Books         0    8048.26
13146     P3544               Lipstick          beauty         2        NaN
13147     P5497          Skipping Rope          SPORTS         2   13349.76
13148     P2141          Fiction Novel           Books         2    2800.22
13149     P9826         Wireless Mouse     Electronics         3    4500.82

       DiscountPercent  TotalAmount         OrderDate          ShipDate  \
0                   25     -7622.21         19-Jun-24  18-06-2024 03:42
1                    5     42573.91        09-17-2023         19-Sep-23
2                  150     -6815.28  18-07-2024 21:05        27-07-2024
3                   20    166027.44  21-02-2022 08:47  25-02-2022 08:47
4                   10     43665.08        30-07-2022        07-08-2022
...                ...          ...               ...               ...
13145                0         0.00        13-07-2022               NaN
13146                0     10237.82  11-01-2023 04:40               NaN
13147                0     26699.52        12-24-2022        30-12-2022
13148               20      4480.35         14-Jan-22  24-01-2022 17:58
13149                0     13502.46        24-07-2022         30-Jul-22

          PaymentMethod OrderStatus ShippingCity    Country  CustomerRating
0                Wallet  cancelled        Sydney  Australia             NaN
1                   COD     Pending          NaN        UAE             6.0
2           Net Banking     Pending       London         UK             3.0
3                wallet     Pending    Singapore  Singapore             6.0
4      Cash on Delivery  processing        SURAT      India             5.0
...                 ...         ...          ...        ...             ...
13145            Paypal   Cancelled        Paris     France             6.0
13146               COD   Delivered        Surat      India             2.0
13147            Wallet   delivered   Manchester        NaN             2.0
13148               EMI   delivered    Singapore        NaN             NaN
13149               UPI     Pending      Chicago        USA             4.0

[13150 rows x 18 columns]>

In [4]:
df.info

<bound method DataFrame.info of          OrderID CustomerID     CustomerName                        Email  \
0      ORD104369   CUST3263     Ayaan Miller    ayaanmiller27@hotmail.com
1      ORD109142   CUST3663       Mia Miller      miamiller52@outlook.com
2      ORD104638   CUST3028    Isabella Iyer     isabellaiyer@hotmail.com
3      ORD111342   CUST1115      David Singh         davidsingh@gmail.com
4      ORD106560   CUST3690     mason garcia        masongarcia@gmail.com
...          ...        ...              ...                          ...
13145  ORD107086   CUST1495   Reyansh Sharma    reyanshsharma71@gmail.com
13146  ORD105562   CUST3602   Krishna Miller  krishnamiller89@outlook.com
13147  ORD103403   CUST3206     Robert Patel        robertpatel@yahoo.com
13148  ORD109055   CUST2522  EVELYN MARTINEZ     evelynmartinez@gmail.com
13149  ORD110475   CUST3255   Amelia Reddy     ameliareddy@rediffmail.com

      ProductID            ProductName        Category  Quantity  UnitPrice  \
0         P7565          Winter Jacket         Fashion        -1   10162.95
1         P2000       Resistance Bands          Sports         4   11203.66
2         P5250  Children's Story Book           books         1   13630.56
3         P7565          Winter Jacket         FASHION        10   20753.43
4         P5284      Kitchen Knife Set  HOME & KITCHEN         5    9703.35
...         ...                    ...             ...       ...        ...
13145     P4418              Biography           Books         0    8048.26
13146     P3544               Lipstick          beauty         2        NaN
13147     P5497          Skipping Rope          SPORTS         2   13349.76
13148     P2141          Fiction Novel           Books         2    2800.22
13149     P9826         Wireless Mouse     Electronics         3    4500.82

       DiscountPercent  TotalAmount         OrderDate          ShipDate  \
0                   25     -7622.21         19-Jun-24  18-06-2024 03:42
1                    5     42573.91        09-17-2023         19-Sep-23
2                  150     -6815.28  18-07-2024 21:05        27-07-2024
3                   20    166027.44  21-02-2022 08:47  25-02-2022 08:47
4                   10     43665.08        30-07-2022        07-08-2022
...                ...          ...               ...               ...
13145                0         0.00        13-07-2022               NaN
13146                0     10237.82  11-01-2023 04:40               NaN
13147                0     26699.52        12-24-2022        30-12-2022
13148               20      4480.35         14-Jan-22  24-01-2022 17:58
13149                0     13502.46        24-07-2022         30-Jul-22

          PaymentMethod OrderStatus ShippingCity    Country  CustomerRating
0                Wallet  cancelled        Sydney  Australia             NaN
1                   COD     Pending          NaN        UAE             6.0
2           Net Banking     Pending       London         UK             3.0
3                wallet     Pending    Singapore  Singapore             6.0
4      Cash on Delivery  processing        SURAT      India             5.0
...                 ...         ...          ...        ...             ...
13145            Paypal   Cancelled        Paris     France             6.0
13146               COD   Delivered        Surat      India             2.0
13147            Wallet   delivered   Manchester        NaN             2.0
13148               EMI   delivered    Singapore        NaN             NaN
13149               UPI     Pending      Chicago        USA             4.0

[13150 rows x 18 columns]>

In [5]:
df.isnull().sum()

OrderID               0
CustomerID          241
CustomerName        554
Email               795
ProductID             0
ProductName         355
Category            415
Quantity              0
UnitPrice           395
DiscountPercent       0
TotalAmount         251
OrderDate           512
ShipDate           2032
PaymentMethod       606
OrderStatus         375
ShippingCity        681
Country             637
CustomerRating     3231
dtype: int64

In [11]:
# Text columns ka whitespace trim karo
df['CustomerName'] = df['CustomerName'].str.strip()
df['Email'] = df['Email'].str.strip()
df['ProductName'] = df['ProductName'].str.strip()
df['Category'] = df['Category'].str.strip()
df['PaymentMethod'] = df['PaymentMethod'].str.strip()
df['OrderStatus'] = df['OrderStatus'].str.strip()
df['ShippingCity'] = df['ShippingCity'].str.strip()
df['Country'] = df['Country'].str.strip()

df.replace(['N/A', 'NA', 'None', ''], np.nan, inplace=True)

,OrderID,CustomerID,CustomerName,Email,ProductID,ProductName,Category,Quantity,UnitPrice,DiscountPercent,TotalAmount,OrderDate,ShipDate,PaymentMethod,OrderStatus,ShippingCity,Country,CustomerRating
0,ORD104369,CUST3263,Ayaan Miller,ayaanmiller27@hotmail.com,P7565,Winter Jacket,Fashion,-1,10162.95,25,-7622.21,19-Jun-24,18-06-2024 03:42,Wallet,cancelled,Sydney,Australia,NaN
1,ORD109142,CUST3663,Mia Miller,miamiller52@outlook.com,P2000,Resistance Bands,Sports,4,11203.66,5,42573.91,09-17-2023,19-Sep-23,COD,Pending,NaN,UAE,6.0
2,ORD104638,CUST3028,Isabella Iyer,isabellaiyer@hotmail.com,P5250,Children's Story Book,books,1,13630.56,150,-6815.28,18-07-2024 21:05,27-07-2024,Net Banking,Pending,London,UK,3.0
3,ORD111342,CUST1115,David Singh,davidsingh@gmail.com,P7565,Winter Jacket,FASHION,10,20753.43,20,166027.44,21-02-2022 08:47,25-02-2022 08:47,wallet,Pending,Singapore,Singapore,6.0
4,ORD106560,CUST3690,mason garcia,masongarcia@gmail.com,P5284,Kitchen Knife Set,HOME & KITCHEN,5,9703.35,10,43665.08,30-07-2022,07-08-2022,Cash on Delivery,processing,SURAT,India,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13145,ORD107086,CUST1495,Reyansh Sharma,reyanshsharma71@gmail.com,P4418,Biography,Books,0,8048.26,0,0.00,13-07-2022,NaN,Paypal,Cancelled,Paris,France,6.0
13146,ORD105562,CUST3602,Krishna Miller,krishnamiller89@outlook.com,P3544,Lipstick,beauty,2,NaN,0,10237.82,11-01-2023 04:40,NaN,COD,Delivered,Surat,India,2.0
13147,ORD103403,CUST3206,Robert Patel,robertpatel@yahoo.com,P5497,Skipping Rope,SPORTS,2,13349.76,0,26699.52,12-24-2022,30-12-2022,Wallet,delivered,Manchester,NaN,2.0
13148,ORD109055,CUST2522,EVELYN MARTINEZ,evelynmartinez@gmail.com,P2141,Fiction Novel,Books,2,2800.22,20,4480.35,14-Jan-22,24-01-2022 17:58,EMI,delivered,Singapore,NaN,NaN
13149,ORD110475,CUST3255,Amelia Reddy,ameliareddy@rediffmail.com,P9826,Wireless Mouse,Electronics,3,4500.82,0,13502.46,24-07-2022,30-Jul-22,UPI,Pending,Chicago,USA,4.0

In [12]:

df['Category'].unique()

<StringArray>
[       'Fashion',         'Sports',          'books',        'FASHION',
 'HOME & KITCHEN',           'Toys',    'electronics',    'ELECTRONICS',
 'Home & Kitchen', 'home & kitchen',         'Beauty',              nan,
          'Books',         'beauty',    'Electronics',         'SPORTS',
           'TOYS',         'sports',          'BOOKS',           'toys',
        'fashion',         'BEAUTY']
Length: 22, dtype: str

In [17]:
df['Category'] = df['Category'].str.title()
df['Category'].unique()

<StringArray>
[       'Fashion',         'Sports',          'Books', 'Home & Kitchen',
           'Toys',    'Electronics',         'Beauty',              nan]
Length: 8, dtype: str

In [19]:
df['PaymentMethod'] = df['PaymentMethod'].str.upper()
df['PaymentMethod'] = df['PaymentMethod'].replace({
    'COD': 'Cash on Delivery',
    'CASH ON DELIVERY': 'Cash on Delivery',
    'WALLET': 'Wallet',
    'NET BANKING': 'Net Banking',
    'DEBIT CARD': 'Debit Card',
    'CREDIT CARD': 'Credit Card',
    'UPI': 'UPI',
    'PAYPAL': 'PayPal',
    'EMI': 'EMI'
})
df

,OrderID,CustomerID,CustomerName,Email,ProductID,ProductName,Category,Quantity,UnitPrice,DiscountPercent,TotalAmount,OrderDate,ShipDate,PaymentMethod,OrderStatus,ShippingCity,Country,CustomerRating
0,ORD104369,CUST3263,Ayaan Miller,ayaanmiller27@hotmail.com,P7565,Winter Jacket,Fashion,-1,10162.95,25,-7622.21,19-Jun-24,18-06-2024 03:42,Wallet,cancelled,Sydney,Australia,NaN
1,ORD109142,CUST3663,Mia Miller,miamiller52@outlook.com,P2000,Resistance Bands,Sports,4,11203.66,5,42573.91,09-17-2023,19-Sep-23,Cash on Delivery,Pending,NaN,UAE,6.0
2,ORD104638,CUST3028,Isabella Iyer,isabellaiyer@hotmail.com,P5250,Children's Story Book,Books,1,13630.56,150,-6815.28,18-07-2024 21:05,27-07-2024,Net Banking,Pending,London,UK,3.0
3,ORD111342,CUST1115,David Singh,davidsingh@gmail.com,P7565,Winter Jacket,Fashion,10,20753.43,20,166027.44,21-02-2022 08:47,25-02-2022 08:47,Wallet,Pending,Singapore,Singapore,6.0
4,ORD106560,CUST3690,mason garcia,masongarcia@gmail.com,P5284,Kitchen Knife Set,Home & Kitchen,5,9703.35,10,43665.08,30-07-2022,07-08-2022,Cash on Delivery,processing,SURAT,India,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13145,ORD107086,CUST1495,Reyansh Sharma,reyanshsharma71@gmail.com,P4418,Biography,Books,0,8048.26,0,0.00,13-07-2022,NaN,PayPal,Cancelled,Paris,France,6.0
13146,ORD105562,CUST3602,Krishna Miller,krishnamiller89@outlook.com,P3544,Lipstick,Beauty,2,NaN,0,10237.82,11-01-2023 04:40,NaN,Cash on Delivery,Delivered,Surat,India,2.0
13147,ORD103403,CUST3206,Robert Patel,robertpatel@yahoo.com,P5497,Skipping Rope,Sports,2,13349.76,0,26699.52,12-24-2022,30-12-2022,Wallet,delivered,Manchester,NaN,2.0
13148,ORD109055,CUST2522,EVELYN MARTINEZ,evelynmartinez@gmail.com,P2141,Fiction Novel,Books,2,2800.22,20,4480.35,14-Jan-22,24-01-2022 17:58,EMI,delivered,Singapore,NaN,NaN
13149,ORD110475,CUST3255,Amelia Reddy,ameliareddy@rediffmail.com,P9826,Wireless Mouse,Electronics,3,4500.82,0,13502.46,24-07-2022,30-Jul-22,UPI,Pending,Chicago,USA,4.0

In [20]:
df['OrderStatus'] = df['OrderStatus'].str.upper()
df['OrderStatus'] = df['OrderStatus'].replace({
    'PENDING': 'Pending',
    'PROCESSING': 'Processing',
    'SHIPPED': 'Shipped',
    'DELIVERED': 'Delivered',
    'DELVERED': 'Delivered',
    'CANCELLED': 'Cancelled',
    'RETURNED': 'Returned',
    'IN TRANSIT': 'In Transit'
})
df

,OrderID,CustomerID,CustomerName,Email,ProductID,ProductName,Category,Quantity,UnitPrice,DiscountPercent,TotalAmount,OrderDate,ShipDate,PaymentMethod,OrderStatus,ShippingCity,Country,CustomerRating
0,ORD104369,CUST3263,Ayaan Miller,ayaanmiller27@hotmail.com,P7565,Winter Jacket,Fashion,-1,10162.95,25,-7622.21,19-Jun-24,18-06-2024 03:42,Wallet,Cancelled,Sydney,Australia,NaN
1,ORD109142,CUST3663,Mia Miller,miamiller52@outlook.com,P2000,Resistance Bands,Sports,4,11203.66,5,42573.91,09-17-2023,19-Sep-23,Cash on Delivery,Pending,NaN,UAE,6.0
2,ORD104638,CUST3028,Isabella Iyer,isabellaiyer@hotmail.com,P5250,Children's Story Book,Books,1,13630.56,150,-6815.28,18-07-2024 21:05,27-07-2024,Net Banking,Pending,London,UK,3.0
3,ORD111342,CUST1115,David Singh,davidsingh@gmail.com,P7565,Winter Jacket,Fashion,10,20753.43,20,166027.44,21-02-2022 08:47,25-02-2022 08:47,Wallet,Pending,Singapore,Singapore,6.0
4,ORD106560,CUST3690,mason garcia,masongarcia@gmail.com,P5284,Kitchen Knife Set,Home & Kitchen,5,9703.35,10,43665.08,30-07-2022,07-08-2022,Cash on Delivery,Processing,SURAT,India,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13145,ORD107086,CUST1495,Reyansh Sharma,reyanshsharma71@gmail.com,P4418,Biography,Books,0,8048.26,0,0.00,13-07-2022,NaN,PayPal,Cancelled,Paris,France,6.0
13146,ORD105562,CUST3602,Krishna Miller,krishnamiller89@outlook.com,P3544,Lipstick,Beauty,2,NaN,0,10237.82,11-01-2023 04:40,NaN,Cash on Delivery,Delivered,Surat,India,2.0
13147,ORD103403,CUST3206,Robert Patel,robertpatel@yahoo.com,P5497,Skipping Rope,Sports,2,13349.76,0,26699.52,12-24-2022,30-12-2022,Wallet,Delivered,Manchester,NaN,2.0
13148,ORD109055,CUST2522,EVELYN MARTINEZ,evelynmartinez@gmail.com,P2141,Fiction Novel,Books,2,2800.22,20,4480.35,14-Jan-22,24-01-2022 17:58,EMI,Delivered,Singapore,NaN,NaN
13149,ORD110475,CUST3255,Amelia Reddy,ameliareddy@rediffmail.com,P9826,Wireless Mouse,Electronics,3,4500.82,0,13502.46,24-07-2022,30-Jul-22,UPI,Pending,Chicago,USA,4.0

In [21]:
print(df['PaymentMethod'].unique())
print(df['OrderStatus'].unique())

<StringArray>
[          'Wallet', 'Cash on Delivery',      'Net Banking',
       'Debit Card',              'UPI',      'Credit Card',
           'PayPal',                nan,              'EMI']
Length: 9, dtype: str
<StringArray>
[ 'Cancelled',    'Pending', 'Processing',    'Shipped',  'Delivered',
 'In Transit',   'Returned',          nan]
Length: 8, dtype: str

In [ ]:
df.duplicated(subset=['OrderID']).sum()

np.int64(650)

In [24]:
df = df.drop_duplicates(subset=['OrderID'], keep='first')
df

,OrderID,CustomerID,CustomerName,Email,ProductID,ProductName,Category,Quantity,UnitPrice,DiscountPercent,TotalAmount,OrderDate,ShipDate,PaymentMethod,OrderStatus,ShippingCity,Country,CustomerRating
0,ORD104369,CUST3263,Ayaan Miller,ayaanmiller27@hotmail.com,P7565,Winter Jacket,Fashion,-1,10162.95,25,-7622.21,19-Jun-24,18-06-2024 03:42,Wallet,Cancelled,Sydney,Australia,NaN
1,ORD109142,CUST3663,Mia Miller,miamiller52@outlook.com,P2000,Resistance Bands,Sports,4,11203.66,5,42573.91,09-17-2023,19-Sep-23,Cash on Delivery,Pending,NaN,UAE,6.0
2,ORD104638,CUST3028,Isabella Iyer,isabellaiyer@hotmail.com,P5250,Children's Story Book,Books,1,13630.56,150,-6815.28,18-07-2024 21:05,27-07-2024,Net Banking,Pending,London,UK,3.0
3,ORD111342,CUST1115,David Singh,davidsingh@gmail.com,P7565,Winter Jacket,Fashion,10,20753.43,20,166027.44,21-02-2022 08:47,25-02-2022 08:47,Wallet,Pending,Singapore,Singapore,6.0
4,ORD106560,CUST3690,mason garcia,masongarcia@gmail.com,P5284,Kitchen Knife Set,Home & Kitchen,5,9703.35,10,43665.08,30-07-2022,07-08-2022,Cash on Delivery,Processing,SURAT,India,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13145,ORD107086,CUST1495,Reyansh Sharma,reyanshsharma71@gmail.com,P4418,Biography,Books,0,8048.26,0,0.00,13-07-2022,NaN,PayPal,Cancelled,Paris,France,6.0
13146,ORD105562,CUST3602,Krishna Miller,krishnamiller89@outlook.com,P3544,Lipstick,Beauty,2,NaN,0,10237.82,11-01-2023 04:40,NaN,Cash on Delivery,Delivered,Surat,India,2.0
13147,ORD103403,CUST3206,Robert Patel,robertpatel@yahoo.com,P5497,Skipping Rope,Sports,2,13349.76,0,26699.52,12-24-2022,30-12-2022,Wallet,Delivered,Manchester,NaN,2.0
13148,ORD109055,CUST2522,EVELYN MARTINEZ,evelynmartinez@gmail.com,P2141,Fiction Novel,Books,2,2800.22,20,4480.35,14-Jan-22,24-01-2022 17:58,EMI,Delivered,Singapore,NaN,NaN
13149,ORD110475,CUST3255,Amelia Reddy,ameliareddy@rediffmail.com,P9826,Wireless Mouse,Electronics,3,4500.82,0,13502.46,24-07-2022,30-Jul-22,UPI,Pending,Chicago,USA,4.0

In [25]:
print(df.shape)
print(df.duplicated(subset=['OrderID']).sum())

(12500, 18)
0

In [26]:
df['OrderDate'] = pd.to_datetime(df['OrderDate'], format='mixed', dayfirst=True, errors='coerce')
df['ShipDate'] = pd.to_datetime(df['ShipDate'], format='mixed', dayfirst=True, errors='coerce')

In [27]:
print(df['OrderDate'].dtype)
print(df['OrderDate'].isnull().sum())
print(df[['OrderDate', 'ShipDate']].head(10))

datetime64[us]
491
            OrderDate            ShipDate
0 2024-06-19 00:00:00 2024-06-18 03:42:00
1 2023-09-17 00:00:00 2023-09-19 00:00:00
2 2024-07-18 21:05:00 2024-07-27 00:00:00
3 2022-02-21 08:47:00 2022-02-25 08:47:00
4 2022-07-30 00:00:00 2022-08-07 00:00:00
5 2023-01-10 00:00:00 2023-01-14 00:00:00
6 2022-03-26 00:00:00 2022-03-25 19:44:00
7 2024-05-09 00:00:00 2024-09-13 00:00:00
8 2023-10-09 00:00:00 2023-10-08 00:00:00
9 2023-05-08 00:00:00 2023-05-08 00:00:00

In [28]:
df.loc[df['ShipDate'] < df['OrderDate'], 'ShipDate'] = pd.NaT

In [29]:
df['OrderDate'].isnull().sum()

np.int64(491)

In [30]:
df_original = pd.read_csv('messy_ecommerce_sales_dataset.csv')
mask = df['OrderDate'].isnull() & df_original['OrderDate'].notnull()
df_original.loc[mask, 'OrderDate'].unique()[:20]

<StringArray>
[]
Length: 0, dtype: str

In [32]:
df['Quantity'] = df['Quantity'].abs()
df

,OrderID,CustomerID,CustomerName,Email,ProductID,ProductName,Category,Quantity,UnitPrice,DiscountPercent,TotalAmount,OrderDate,ShipDate,PaymentMethod,OrderStatus,ShippingCity,Country,CustomerRating
0,ORD104369,CUST3263,Ayaan Miller,ayaanmiller27@hotmail.com,P7565,Winter Jacket,Fashion,1,10162.95,25,-7622.21,2024-06-19 00:00:00,NaT,Wallet,Cancelled,Sydney,Australia,NaN
1,ORD109142,CUST3663,Mia Miller,miamiller52@outlook.com,P2000,Resistance Bands,Sports,4,11203.66,5,42573.91,2023-09-17 00:00:00,2023-09-19 00:00:00,Cash on Delivery,Pending,NaN,UAE,6.0
2,ORD104638,CUST3028,Isabella Iyer,isabellaiyer@hotmail.com,P5250,Children's Story Book,Books,1,13630.56,150,-6815.28,2024-07-18 21:05:00,2024-07-27 00:00:00,Net Banking,Pending,London,UK,3.0
3,ORD111342,CUST1115,David Singh,davidsingh@gmail.com,P7565,Winter Jacket,Fashion,10,20753.43,20,166027.44,2022-02-21 08:47:00,2022-02-25 08:47:00,Wallet,Pending,Singapore,Singapore,6.0
4,ORD106560,CUST3690,mason garcia,masongarcia@gmail.com,P5284,Kitchen Knife Set,Home & Kitchen,5,9703.35,10,43665.08,2022-07-30 00:00:00,2022-08-07 00:00:00,Cash on Delivery,Processing,SURAT,India,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13145,ORD107086,CUST1495,Reyansh Sharma,reyanshsharma71@gmail.com,P4418,Biography,Books,0,8048.26,0,0.00,2022-07-13 00:00:00,NaT,PayPal,Cancelled,Paris,France,6.0
13146,ORD105562,CUST3602,Krishna Miller,krishnamiller89@outlook.com,P3544,Lipstick,Beauty,2,NaN,0,10237.82,2023-01-11 04:40:00,NaT,Cash on Delivery,Delivered,Surat,India,2.0
13147,ORD103403,CUST3206,Robert Patel,robertpatel@yahoo.com,P5497,Skipping Rope,Sports,2,13349.76,0,26699.52,2022-12-24 00:00:00,2022-12-30 00:00:00,Wallet,Delivered,Manchester,NaN,2.0
13148,ORD109055,CUST2522,EVELYN MARTINEZ,evelynmartinez@gmail.com,P2141,Fiction Novel,Books,2,2800.22,20,4480.35,2022-01-14 00:00:00,2022-01-24 17:58:00,EMI,Delivered,Singapore,NaN,NaN
13149,ORD110475,CUST3255,Amelia Reddy,ameliareddy@rediffmail.com,P9826,Wireless Mouse,Electronics,3,4500.82,0,13502.46,2022-07-24 00:00:00,2022-07-30 00:00:00,UPI,Pending,Chicago,USA,4.0

In [34]:
df.loc[df['DiscountPercent'] > 100, 'DiscountPercent'] = np.nan
df

,OrderID,CustomerID,CustomerName,Email,ProductID,ProductName,Category,Quantity,UnitPrice,DiscountPercent,TotalAmount,OrderDate,ShipDate,PaymentMethod,OrderStatus,ShippingCity,Country,CustomerRating
0,ORD104369,CUST3263,Ayaan Miller,ayaanmiller27@hotmail.com,P7565,Winter Jacket,Fashion,1,10162.95,25.0,-7622.21,2024-06-19 00:00:00,NaT,Wallet,Cancelled,Sydney,Australia,NaN
1,ORD109142,CUST3663,Mia Miller,miamiller52@outlook.com,P2000,Resistance Bands,Sports,4,11203.66,5.0,42573.91,2023-09-17 00:00:00,2023-09-19 00:00:00,Cash on Delivery,Pending,NaN,UAE,6.0
2,ORD104638,CUST3028,Isabella Iyer,isabellaiyer@hotmail.com,P5250,Children's Story Book,Books,1,13630.56,NaN,-6815.28,2024-07-18 21:05:00,2024-07-27 00:00:00,Net Banking,Pending,London,UK,3.0
3,ORD111342,CUST1115,David Singh,davidsingh@gmail.com,P7565,Winter Jacket,Fashion,10,20753.43,20.0,166027.44,2022-02-21 08:47:00,2022-02-25 08:47:00,Wallet,Pending,Singapore,Singapore,6.0
4,ORD106560,CUST3690,mason garcia,masongarcia@gmail.com,P5284,Kitchen Knife Set,Home & Kitchen,5,9703.35,10.0,43665.08,2022-07-30 00:00:00,2022-08-07 00:00:00,Cash on Delivery,Processing,SURAT,India,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13145,ORD107086,CUST1495,Reyansh Sharma,reyanshsharma71@gmail.com,P4418,Biography,Books,0,8048.26,0.0,0.00,2022-07-13 00:00:00,NaT,PayPal,Cancelled,Paris,France,6.0
13146,ORD105562,CUST3602,Krishna Miller,krishnamiller89@outlook.com,P3544,Lipstick,Beauty,2,NaN,0.0,10237.82,2023-01-11 04:40:00,NaT,Cash on Delivery,Delivered,Surat,India,2.0
13147,ORD103403,CUST3206,Robert Patel,robertpatel@yahoo.com,P5497,Skipping Rope,Sports,2,13349.76,0.0,26699.52,2022-12-24 00:00:00,2022-12-30 00:00:00,Wallet,Delivered,Manchester,NaN,2.0
13148,ORD109055,CUST2522,EVELYN MARTINEZ,evelynmartinez@gmail.com,P2141,Fiction Novel,Books,2,2800.22,20.0,4480.35,2022-01-14 00:00:00,2022-01-24 17:58:00,EMI,Delivered,Singapore,NaN,NaN
13149,ORD110475,CUST3255,Amelia Reddy,ameliareddy@rediffmail.com,P9826,Wireless Mouse,Electronics,3,4500.82,0.0,13502.46,2022-07-24 00:00:00,2022-07-30 00:00:00,UPI,Pending,Chicago,USA,4.0

In [35]:
print(df['Quantity'].min())
print(df['DiscountPercent'].max())
print(df['DiscountPercent'].isnull().sum())

0
50.0
1236

In [36]:
df.loc[df['Quantity'] == 0, 'Quantity'] = np.nan
print(df['Quantity'].min())
print(df['Quantity'].isnull().sum())

1.0
1140

In [41]:
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())
df['DiscountPercent'] = df['DiscountPercent'].fillna(df['DiscountPercent'].median())
df['UnitPrice'] = df.groupby('ProductName')['UnitPrice'].transform(lambda x: x.fillna(x.median()))
df['UnitPrice'] = df['UnitPrice'].fillna(df['UnitPrice'].median())
df

,OrderID,CustomerID,CustomerName,Email,ProductID,ProductName,Category,Quantity,UnitPrice,DiscountPercent,TotalAmount,OrderDate,ShipDate,PaymentMethod,OrderStatus,ShippingCity,Country,CustomerRating
0,ORD104369,CUST3263,Ayaan Miller,ayaanmiller27@hotmail.com,P7565,Winter Jacket,Fashion,1.0,10162.95,25.0,-7622.21,2024-06-19 00:00:00,NaT,Wallet,Cancelled,Sydney,Australia,NaN
1,ORD109142,CUST3663,Mia Miller,miamiller52@outlook.com,P2000,Resistance Bands,Sports,4.0,11203.66,5.0,42573.91,2023-09-17 00:00:00,2023-09-19 00:00:00,Cash on Delivery,Pending,NaN,UAE,6.0
2,ORD104638,CUST3028,Isabella Iyer,isabellaiyer@hotmail.com,P5250,Children's Story Book,Books,1.0,13630.56,10.0,-6815.28,2024-07-18 21:05:00,2024-07-27 00:00:00,Net Banking,Pending,London,UK,3.0
3,ORD111342,CUST1115,David Singh,davidsingh@gmail.com,P7565,Winter Jacket,Fashion,10.0,20753.43,20.0,166027.44,2022-02-21 08:47:00,2022-02-25 08:47:00,Wallet,Pending,Singapore,Singapore,6.0
4,ORD106560,CUST3690,mason garcia,masongarcia@gmail.com,P5284,Kitchen Knife Set,Home & Kitchen,5.0,9703.35,10.0,43665.08,2022-07-30 00:00:00,2022-08-07 00:00:00,Cash on Delivery,Processing,SURAT,India,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13145,ORD107086,CUST1495,Reyansh Sharma,reyanshsharma71@gmail.com,P4418,Biography,Books,2.0,8048.26,0.0,0.00,2022-07-13 00:00:00,NaT,PayPal,Cancelled,Paris,France,6.0
13146,ORD105562,CUST3602,Krishna Miller,krishnamiller89@outlook.com,P3544,Lipstick,Beauty,2.0,11367.45,0.0,10237.82,2023-01-11 04:40:00,NaT,Cash on Delivery,Delivered,Surat,India,2.0
13147,ORD103403,CUST3206,Robert Patel,robertpatel@yahoo.com,P5497,Skipping Rope,Sports,2.0,13349.76,0.0,26699.52,2022-12-24 00:00:00,2022-12-30 00:00:00,Wallet,Delivered,Manchester,NaN,2.0
13148,ORD109055,CUST2522,EVELYN MARTINEZ,evelynmartinez@gmail.com,P2141,Fiction Novel,Books,2.0,2800.22,20.0,4480.35,2022-01-14 00:00:00,2022-01-24 17:58:00,EMI,Delivered,Singapore,NaN,NaN
13149,ORD110475,CUST3255,Amelia Reddy,ameliareddy@rediffmail.com,P9826,Wireless Mouse,Electronics,3.0,4500.82,0.0,13502.46,2022-07-24 00:00:00,2022-07-30 00:00:00,UPI,Pending,Chicago,USA,4.0

In [42]:
print(df['Quantity'].isnull().sum())
print(df['DiscountPercent'].isnull().sum())
print(df['UnitPrice'].isnull().sum())

0
0
0

TotalAmount = Quantity × UnitPrice × (1 - Discount/100)

In [43]:
df['TotalAmount'] = df['Quantity'] * df['UnitPrice'] * (1 - df['DiscountPercent'] / 100)
df['TotalAmount'] = df['TotalAmount'].round(2)

In [44]:
print(df['TotalAmount'].min())
print(df['TotalAmount'].isnull().sum())
df[['Quantity', 'UnitPrice', 'DiscountPercent', 'TotalAmount']].head(10)

-242730.6
0

   Quantity  UnitPrice  DiscountPercent  TotalAmount
0       1.0   10162.95             25.0      7622.21
1       4.0   11203.66              5.0     42573.91
2       1.0   13630.56             10.0     12267.50
3      10.0   20753.43             20.0    166027.44
4       5.0    9703.35             10.0     43665.08
5       3.0   12039.53             10.0     32506.73
6       1.0     564.40             20.0       451.52
7       1.0   11947.83             15.0     10155.66
8       1.0   12710.86              0.0     12710.86
9       1.0   12878.74             10.0     11590.87

In [46]:
df[df['Email'].notnull() & ~df['Email'].str.contains('@', na=False)]['Email'].head(10)

5            ethansmithyahoo.com
9      saanvipatelrediffmail.com
37        sophiareddyhotmail.com
38       ishakumarrediffmail.com
40     ishaanwilliamshotmail.com
72            johnsmithyahoo.com
81         riyawilliamsyahoo.com
101          vivaannairgmail.com
113      anikapatel65outlook.com
128       adityakumaroutlook.com
Name: Email, dtype: str

In [47]:
domains = ['gmail.com', 'yahoo.com', 'hotmail.com', 'outlook.com', 'rediffmail.com']

for d in domains:
    mask = df['Email'].notnull() & ~df['Email'].str.contains('@', na=False) & df['Email'].str.endswith(d)
    df.loc[mask, 'Email'] = df.loc[mask, 'Email'].str.replace(d, '@' + d, regex=False)

In [48]:
broken_emails_after = df[df['Email'].notnull() & ~df['Email'].str.contains('@', na=False)]
print(broken_emails_after.shape)
df[df['Email'].str.contains('@', na=False)]['Email'].head(15)

(0, 18)

0       ayaanmiller27@hotmail.com
1         miamiller52@outlook.com
2        isabellaiyer@hotmail.com
3            davidsingh@gmail.com
4           masongarcia@gmail.com
5            ethansmith@yahoo.com
6       isabellakumar55@yahoo.com
7            aaravbrown@yahoo.com
8       miawilliams36@hotmail.com
9      saanvipatel@rediffmail.com
11             priyadas@yahoo.com
12          aadhyapatel@gmail.com
13            myradas97@yahoo.com
14    krishnakumar@rediffmail.com
15         michaeldas@hotmail.com
Name: Email, dtype: str

In [49]:
df['Category'] = df['Category'].fillna('Unknown')
df['PaymentMethod'] = df['PaymentMethod'].fillna('Unknown')
df['OrderStatus'] = df['OrderStatus'].fillna('Unknown')
df['ShippingCity'] = df['ShippingCity'].fillna('Unknown')
df['Country'] = df['Country'].fillna('Unknown')
df['CustomerName'] = df['CustomerName'].fillna('Unknown')
df['ProductName'] = df['ProductName'].fillna('Unknown')

In [50]:
df.isnull().sum()

OrderID               0
CustomerID          233
CustomerName          0
Email               757
ProductID             0
ProductName           0
Category              0
Quantity              0
UnitPrice             0
DiscountPercent       0
TotalAmount           0
OrderDate           491
ShipDate           4070
PaymentMethod         0
OrderStatus           0
ShippingCity          0
Country               0
CustomerRating     3069
dtype: int64

In [51]:
df.to_csv('cleaned_sales_data.csv', index=False)
print("Saved successfully! Shape:", df.shape)

Saved successfully! Shape: (12500, 18)

In [57]:
!pip install mysql-connector-python sqlalchemy pymysql

Collecting mysql-connector-python
  Downloading mysql_connector_python-26.7.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: sqlalchemy in C:\Users\Himanshu Mishra\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.0.52)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in C:\Users\Himanshu Mishra\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Himanshu Mishra\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.15.0)
Downloading mysql_connector_python-26.7.0-cp314-cp314-win_amd64.whl (18.2 MB)
   ---------------------------------------- 0.0/18.2 MB ? eta -:--:--
   - -------------------------------------- 0.8/18.2 MB 7.6 MB/s eta 0:00:03
   --- ------------------------------------ 1.6/18.2 MB 4.6 MB/s eta 0:00:04
   ----- ---------------------------------- 2.4/18.2 MB 4.3 MB/s eta 0:00:04
   ------ --------------------------------- 3.1/18.2 MB 4.2 MB/s eta 0:00:04
   -------- ------------------------------- 3.9/18.2 MB 4.2 MB/s eta 0:00:04
   ---------- ----------------------------- 5.0/18.2 MB 4.1 MB/s eta 0:00:04
   ------------ --------------------------- 5.8/18.2 MB 4.1 MB/s eta 0:00:04
   -------------- ------------------------- 6.6/18.2 MB 4.0 MB/s eta 0:00:03
   ---------------- ----------------------- 7.3/18.2 MB 4.0 MB/s eta 0:00:03
   ----------------- ---------------------- 8.1/18.2 MB 4.0 MB/s eta 0:00:03
   -------------------- ------------------- 9.2/18.2 MB 4.0 MB/s eta 0:00:03
   --------------------- ------------------ 10.0/18.2 MB 4.0 MB/s eta 0:00:03
   ----------------------- ---------------- 10.7/18.2 MB 4.0 MB/s eta 0:00:02
   ------------------------- -------------- 11.5/18.2 MB 4.0 MB/s eta 0:00:02
   --------------------------- ------------ 12.3/18.2 MB 4.0 MB/s eta 0:00:02
   ----------------------------- ---------- 13.4/18.2 MB 4.0 MB/s eta 0:00:02
   ------------------------------- -------- 14.2/18.2 MB 4.0 MB/s eta 0:00:02
   -------------------------------- ------- 14.9/18.2 MB 4.0 MB/s eta 0:00:01
   ---------------------------------- ----- 15.7/18.2 MB 4.0 MB/s eta 0:00:01
   ------------------------------------ --- 16.5/18.2 MB 3.9 MB/s eta 0:00:01
   -------------------------------------- - 17.3/18.2 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  18.1/18.2 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 18.2/18.2 MB 3.9 MB/s  0:00:04
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql, mysql-connector-python

   ---------------------------------------- 0/2 [pymysql]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   ---------------------------------------- 2/2 [mysql-connector-python]

Successfully installed mysql-connector-python-26.7.0 pymysql-1.2.0

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [65]:
from sqlalchemy import create_engine

username = 'root'
password = 'mishra'
host = 'localhost'
database = 'ecommerce_sales'

engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}/{database}')

df.to_sql('sales', engine, if_exists='replace', index=False)

print("Data MySQL me load ho gaya!")

Data MySQL me load ho gaya!